FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

ARG SSH_PUBKEY
RUN apt-get -y update && \
    apt-get -y install git openssh-server python3-pip && \
    mkdir -p /root/.ssh && \
    echo "$SSH_PUBKEY" > /root/.ssh/authorized_keys && \
    echo 'X11UseLocalhost no' >> /etc/ssh/sshd_config

RUN pip3 install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

COPY requirements.txt /tmp
RUN apt-get -y install x11-apps vim

RUN echo 'alias python=python3' >> /root/.bashrc
RUN echo 'alias pip=pip3' >> /root/.bashrc
RUN pip3 install -r /tmp/requirements.txt

EXPOSE 22
VOLUME /workspace

ENTRYPOINT service ssh restart && bash
